# Generated by Django 5.1.4 on 2025-01-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0047_auto_20210308_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master',
            name='product_name',
            field=models.CharField(help_text='Must be of length less than 25', max_length=225),
        ),
    ]
